### ISSUE TITLE
Add an option for disable button

### ISSUE THREAD

**Issue by rlazom** [anirudhsharma392/Slider-Button#10]
Is just that, 
Add a behavior similar to regular buttons, or maybe by default when the function is null.

Thanks in advance for your great job with this plugin

**Comment by jacksonw765** [comment]
I would really like this as well.

**Comment by anirudhsharma392** [comment]
Sure, will change the behaviour similar to regular buttons soon.

**Comment by rish07** [comment]
@anirudhsharma392 Does this issue still exist? If not, I would like to make a PR to fix this

**Comment by anirudhsharma392** [comment]
@rish07 yeah you can create pr
