### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method vibrate on channel vibration)

### ISSUE THREAD

**Issue by krishnaaro** [anirudhsharma392/Slider-Button#2]
on sliding, i'm getting this. but functionality wise its happening fine.

please let me know if i'm missing anythings.

**Comment by anirudhsharma392** [comment]
It gives error because may be you are running it on emulator or
your device don't support vibration.
You can just disable the vibration to be on the safer side.
I'll try to resolve it.
Thanks

**Comment by ghost** [comment]
A simple fix would just check if it's real device, if not disable
