### ISSUE TITLE
Merge null-safety and add desktop support

### ISSUE THREAD

**Issue by Ch4rl3B** [anirudhsharma392/Slider-Button#20]
Please, I see it's a pull request that adds null safety... it would be nice if you merge it.

I may also contribute to add Desktop support if you are interested.. this is a great job, don't let it unmantained.

**Comment by Ch4rl3B** [comment]
Please merge the null-safety pull request!!!

**Comment by AgustinV08** [comment]
You can use the null safety pull request by adding in pubspec.yaml this code

```
  slider_button:
    git:
      url: https://github.com/julianodportela/Slider-Button
```

and running flutter pub get in the terminal
