### ISSUE TITLE
Slider Button throws an exception.

### ISSUE THREAD

**Issue by AliAAli1** [anirudhsharma392/Slider-Button#21]
The following NoSuchMethodError was thrown during paint():
The method 'toPaint' was called on null.
Receiver: null
Tried calling: toPaint()

The relevant error-causing widget was
SliderButton
lib\components\sheets.dart:248
When the exception was thrown, this was the stack
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      _BoxDecorationPainter._paintShadows
package:flutter/…/painting/box_decoration.dart:436
#2      _BoxDecorationPainter.paint
package:flutter/…/painting/box_decoration.dart:482
#3      RenderDecoratedBox.paint
package:flutter/…/rendering/proxy_box.dart:2146
#4      RenderObject._paintWithContext
package:flutter/…/rendering/object.dart:2322
...

**Comment by lexprimost** [comment]
same issue here . did you find a solution ?

**Comment by lexprimost** [comment]
mine was in a listview so i wrapped the sliderbutton with the expanded widget and it works

**Comment by lexprimost** [comment]
i wrapped it in a container and it works fine now

**Comment by tjmeal** [comment]
Same problem, and wrapping into Container doesnt solve the problem for me. Is there any solution comming ?

**Comment by Hasilt** [comment]
workaround is to add boxshadow to SliderButton.

**Comment by harmispatel** [comment]
Do like this 

<code>
Container(
      child: SliderButton(
        action: () {
          ///Do something here
          Navigator.of(context).pop();
        },
        label: Text(
          "Slide to cancel Event",
          style: TextStyle(
              color: Color(0xff4a4a4a), fontWeight: FontWeight.w500, fontSize: 17),
        ),
        icon: Text(
          "x",
          style: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.w400,
            fontSize: 44,
          ),
        ),
        boxShadow: BoxShadow(
          color: Theme.of(context).primaryColor,
          blurRadius: 2.0,
          spreadRadius: 2.0,
          offset: Offset.zero
        ),
      ),
    )
<code>
