### ISSUE TITLE
action: doesn't work with any method

### ISSUE THREAD

**Issue by i-zanis** [anirudhsharma392/Slider-Button#27]
A lot of work has been put into this widget. It is great.

There is a problem with the action, it does not fire anything. 

Many thanks.

  action: () {
                    print("--------------------------");
                  },

**Comment by fly-qp** [comment]
I had the same issue.
I viewed the code. It seems dismiss trashold is default 1.0 in the lib. (The button uses Dismissble to recognize the action) 
Just reduce it to like .8 and it should work fine. (-;

Read the docs about dismissThresholds here: https://api.flutter.dev/flutter/widgets/Dismissible/dismissThresholds.html 

Hope i could help (-:

**Comment by junkkung** [comment]
> I had the same issue. I viewed the code. It seems dismiss trashold is default 1.0 in the lib. (The button uses Dismissble to recognize the action) Just reduce it to like .8 and it should work fine. (-;
> 
> Read the docs about dismissThresholds here: https://api.flutter.dev/flutter/widgets/Dismissible/dismissThresholds.html
> 
> Hope i could help (-:


This work for me. Thank!!!

`sliderButtion(..., dismissThresholds: 0.8, ...) `

**Comment by anirudhsharma392** [comment]
This should be resolved in version 2.0.0
