### ISSUE TITLE
Not working in flutter 2.8

### ISSUE THREAD

**Issue by soumajitgh** [anirudhsharma392/Slider-Button#28]
Please help i want to use the 2.8 performance advantage

**Comment by junkkung** [comment]
I have same problem too. I have tried to change dismissThresholds from its dependency code but still not work.

**Comment by mmolaei7878** [comment]
same probelm with 2.8.1

**Comment by ryor1986** [comment]
same problem. action event is not called when slide.

**Comment by anirudhsharma392** [comment]
This should be resolved in version 2.0.0
