### ISSUE TITLE
Dismissible : false issue

### ISSUE THREAD

**Issue by ifasdev** [anirudhsharma392/Slider-Button#29]
Dear ,

When we use dismissible : false in Slider button, the following issue comes

A dismissed Dismissible widget is still part of the tree.
The following assertion was thrown building Dismissible-[<'cancel'>](dirty, dependencies: [Directionality, _EffectiveTickerMode], state: _DismissibleState#49402(tickers: tracking 2 tickers)):
A dismissed Dismissible widget is still part of the tree.

Make sure to implement the onDismissed handler and to immediately remove the Dismissible widget from the application once that handler has fired.

The relevant error-causing widget was: 
  SliderButton SliderButton:file:///D:/Android/gppl_order_app/lib/screens/home.dart:97:38
When the exception was thrown, this was the stack: 
#0      _DismissibleState.build.<anonymous closure> (package:flutter/src/widgets/dismissible.dart:619:11)
#1      _DismissibleState.build (package:flutter/src/widgets/dismissible.dart:628:8)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4705:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4588:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#6      StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#8      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5626:32)
#9      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6284:17)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#19     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#24     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#30     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#32     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5626:32)
#33     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6284:17)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#39     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#41     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5626:32)
#42     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6284:17)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#44     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5626:32)
#45     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6284:17)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#49     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#53     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#57     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#61     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#64     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#65     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#67     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5626:32)
#68     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6284:17)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#71     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#73     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#77     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#80     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#81     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#82     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#84     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#87     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#88     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#90     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#93     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#94     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#95     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#98     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#100    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#103    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#104    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#107    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#108    StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#111    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#112    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#113    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#114    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#116    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#117    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#120    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#121    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#122    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#123    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#125    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#126    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#127    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#128    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#131    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2578:33)
#132    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#133    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#134    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#135    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#136    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#140    _invoke (dart:ui/hooks.dart:150:10)
#141    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#142    _drawFrame (dart:ui/hooks.dart:114:31)
(elided 3 frames from dart:async)

Please resolve

Thanks

**Comment by Zarathos1084** [comment]
I am getting the same issue, please release a fix for this, thank you :)

**Comment by am2074** [comment]
Got the same issue. Any updates?

**Comment by Aderiani** [comment]
I have the same issue

**Comment by IlyesYhy** [comment]
To solve this issue ctrl+click on the slider button widget and in your slider.dart file replace 
`key: Key("cancel")`
by
`key: UniqueKey()`
in your Dismissible widget (L.~146)

This is due to the fact that your key isn't unique.

More infos [here](https://www.kindacode.com/article/flutter-a-dismissed-dismissible-widget-is-still-part-of-the-tree/#:~:text=When%20working%20with%20the%20Dismissible%20widget%20in%20Flutter%2C%20you%20may,once%20that%20handler%20has%20fired.).

**Comment by da-nish** [comment]
I have already fixed this issue, you can use the package from my GitHub repo

In pubspec.yaml:


```
  slider_button:
    git: "https://github.com/da-nish/Slider-Button"
```

**Comment by anirudhsharma392** [comment]
removed dismissible, Changed action to callback of type Future<bool> Function(), now u can return false to avoid the button to dismiss.
