### ISSUE TITLE
No implementation found for method vibrate on channel vibration

### ISSUE THREAD

**Issue by azamatdev** [anirudhsharma392/Slider-Button#3]
First of all, thank you for this library, it is awesome. But i had an issue with the vibration. When I run the application,  it gives an exception saying MissingPLuginException. I made vibrationFlag true.

`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method vibrate on channel vibration)
E/flutter (27322): #0      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:319
E/flutter (27322): <asynchronous suspension>
E/flutter (27322): #1      Vibration.vibrate 
package:slider_button/src/vibration.dart:48
E/flutter (27322): #2      _SliderButtonState._control.<anonymous closure> 
package:slider_button/src/slider.dart:128
E/flutter (27322): #3      _DismissibleState._handleResizeProgressChanged 
package:flutter/…/widgets/dismissible.dart:500
E/flutter (27322): #4      AnimationLocalListenersMixin.notifyListeners 
package:flutter/…/animation/listener_helpers.dart:124
E/flutter (27322): #5      AnimationController._tick 
package:flutter/…/animation/animation_controller.dart:788
E/flutter (27322): #6      Ticker._tick 
package:flutter/…/scheduler/ticker.dart:237
E/flutter (27322): #7      SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1102
E/flutter (27322): #8      SchedulerBinding.handleBeginFrame.<anonymous closure> 
package:flutter/…/scheduler/binding.dart:1017
E/flutter (27322): #9      _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (27322): #10     SchedulerBinding.handleBeginFrame 
package:flutter/…/scheduler/binding.dart:1015
E/flutter (27322): #11     SchedulerBinding._handleBeginFrame 
package:flutter/…/scheduler/binding.dart:949
E/flutter (27322): #12     _rootRunUnary  (dart:async/zone.dart:1138:13)
E/flutter (27322): #13     _CustomZone.runUnary  (dart:async/zone.dart:1031:19)
E/flutter (27322): #14     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:933:7)
E/flutter (27322): #15     _invoke1  (dart:ui/hooks.dart:273:10)
E/flutter (27322): #16     _beginFrame  (dart:ui/hooks.dart:200:3)`

**Comment by ghost** [comment]
This needs to be gracefully handled. But this won't affect real device, it's on simulator where you don't have a vibrator

**Comment by anirudhsharma392** [comment]
Yeah, it gives exception when vibrator is missing.
Will handle it probably this week.

**Comment by eliasjtg** [comment]
Test in real device, same issue

**Comment by ghost** [comment]
I figured out later. The missing dependencies on the Vibrate library is the culprit. Also a side note, the "Shimmer" library should be declared as 3rd party dependencies. Copy pasted code is always a redflag.

**Comment by anirudhsharma392** [comment]
Handled this exception.

**Comment by MuhammamdArslanKhan** [comment]
facing same issue how to fix it? I even use shimmer plugin separately as well in pubspec.yaml file. using real device
