### ISSUE TITLE
Null Safety Error after installing package

### ISSUE THREAD

**Issue by mdkamrulamin** [anirudhsharma392/Slider-Button#31]
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:vibration

**Comment by Surya092** [comment]
I am facing the same issue while accessing the package

**Comment by aihdeveloper** [comment]
same issue please fix it Thank you

**Comment by tbsmanish** [comment]
try this package with null safety https://pub.dev/packages/buttons_flutter
