### ISSUE TITLE
Feature request: Ability to provide my own widget for the toggle button

### ISSUE THREAD

**Issue by ghost** [anirudhsharma392/Slider-Button#4]
Thanks for this great widget!
Current I can only adjust corner radius. I would prefer having more flexibility by just providing a widget. I need rounded rectangle. The toggle is currently fixed either circle or square.

**Comment by anirudhsharma392** [comment]
Will try to add this feature soon.

**Comment by anirudhsharma392** [comment]
I have added your requested feature.
