### ISSUE TITLE
Hardcoded "60" width edge inset 

### ISSUE THREAD

**Issue by pixnbit** [anirudhsharma392/Slider-Button#6]
Depends on the height and width of the control widget, the hardcoded 60 offset is the culprit:

```
          child: Container(
            width: widget.width - 60,
            height: widget.height,
            alignment: Alignment.centerLeft,
            padding: EdgeInsets.only(
```

![image](https://user-images.githubusercontent.com/729730/75201108-69908080-571c-11ea-8c89-39bbdff76245.png)

**Comment by anirudhsharma392** [comment]
Will try to fix this soon.

**Comment by anirudhsharma392** [comment]
OK, now it's fixed.
