### ISSUE TITLE
No implementation found for method hasVibrator on channel vibration

### ISSUE THREAD

**Issue by waqaskhan409** [anirudhsharma392/Slider-Button#9]
I'm using a real device XIAOMI Redmi note 8 pro and facing this error while using this slider package, can you please resolve this issue in order to maintain the work?

...
 SliderButton(
                          action: () {
                            ///Do something here OnSlide
                          },

                          ///Put label over here
                          label: Text(
                            "Slide to cancel !",
                            style: TextStyle(
                                color: Color(0xff4a4a4a),
                                fontWeight: FontWeight.w500,
                                fontSize: 17),
                          ),
                          icon: Center(
                              child: Icon(
                                Icons.power_settings_new,
                                color: Colors.white,
                                size: 40.0,
                                semanticLabel: 'Text to announce in accessibility modes',
                              )),

                          ///Change All the color and size from here.
                          width: 230,
                          dismissible: true,
                          radius: 10,
                          buttonColor: Color(0xffd60000),
                          backgroundColor: Color(0xff534bae),
                          highlightedColor: Colors.white,
                          baseColor: Colors.red,

                        )
...

E/flutter (17877): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method hasVibrator on channel vibration)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
E/flutter (17877): <asynchronous suspension>
E/flutter (17877): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (17877): #2      Vibration.hasVibrator (package:slider_button/src/vibration.dart:20:43)
E/flutter (17877): #3      _SliderButtonState._control.<anonymous closure> (package:slider_button/src/slider.dart:129:61)
E/flutter (17877): #4      _DismissibleState._handleResizeProgressChanged (package:flutter/src/widgets/dismissible.dart:506:27)
E/flutter (17877): #5      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:137:19)
E/flutter (17877): #6      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:798:5)
E/flutter (17877): #7      Ticker._tick (package:flutter/src/scheduler/ticker.dart:240:12)
E/flutter (17877): #8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
E/flutter (17877): #9      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1032:11)
E/flutter (17877): #10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (17877): #11     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1030:17)
E/flutter (17877): #12     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:964:5)
E/flutter (17877): #13     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (17877): #14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (17877): #15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (17877): #16     _invoke1 (dart:ui/hooks.dart:267:10)
E/flutter (17877): #17     _beginFrame (dart:ui/hooks.dart:194:3)
E/flutter (17877):

**Comment by natget21** [comment]
i am having the same issue i am using M10 android 10 tried enabling or disabling the vibrateflag but still dont work

**Comment by AxesandGrinds** [comment]
I'm having the same issue. Action doesn't fire because of this issue.

**Comment by anirudhsharma392** [comment]
It's resolved in the new version

**Comment by waqaskhan409** [comment]
Thank you @anirudhsharma392
